"""nitial migration

Revision ID: 4904758bc5b7
Revises: 
Create Date: 2026-05-01 03:59:11.870996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4904758bc5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pending_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_registration_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_registration_username'), ['username'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('email_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_email', sa.String(length=120), nullable=True),
    sa.Column('new_email', sa.String(length=120), nullable=False),
    sa.Column('old_email_code', sa.String(length=10), nullable=True),
    sa.Column('new_email_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_change_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_change_request_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('trainings_per_week', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('maintenance_calories', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('water_l', sa.Float(), nullable=False),
    sa.Column('calorie_range_key', sa.String(length=50), nullable=False),
    sa.Column('meal_plan_options_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('substitutions_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_plans_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_plans_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_code_user_id'), ['user_id'], unique=False)

    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=300), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('reps_beginner', sa.String(length=50), nullable=True),
    sa.Column('reps_intermediate', sa.String(length=50), nullable=True),
    sa.Column('reps_advanced', sa.String(length=50), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    op.drop_table('workout')
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscription_user_id'))

    op.drop_table('user_subscription')
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_code_email'))

    op.drop_table('password_reset_code')
    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_plans_is_current'))

    op.drop_table('nutrition_plans')
    with op.batch_alter_table('email_change_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_change_request_user_id'))

    op.drop_table('email_change_request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('pending_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_registration_username'))
        batch_op.drop_index(batch_op.f('ix_pending_registration_email'))

    op.drop_table('pending_registration')
    op.drop_table('muscle_group')
    # ### end Alembic commands ###
